name: tictactoe

services:
    react_client:
        container_name: tictactoe_fe
        image: iarghadip/tictactoe-fe:latest
        build:
            context: ../client
            args:
                - SERVER_KEY=${SERVER_KEY}
        ports:
            - "3000:80"

volumes:
    data: