export const SERVER_OPCODE = {
    GAME_START: 11,
    GAME_STATE: 12,
    GAME_OVER: 13,
    REMATCH_START: 14,
    MATCH_ENDED: 15,
    REMATCH_VOTED: 16,
    TIMER_UPDATE: 17,
    OPPONENT_DISCONNECTED: 18,
    OPPONENT_RECONNECTED: 19,
};

export const CLIENT_OPCODE = {
    MOVE: 21,
    REMATCH_VOTE: 22,
    LEAVE: 23,
};