name: tictactoe

services:
    cockroachdb:
        container_name: tictactoe_db
        image: cockroachdb/cockroach:latest-v23.1
        command: start-single-node --insecure --store=attrs=ssd,path=/var/lib/cockroach/ --max-offset=5s
        restart: "no"
        volumes:
            - data:/var/lib/cockroach
        expose:
            - "8080"
            - "26257"
        ports:
            - "26257:26257"
            - "8080:8080"

    nakama:
        container_name: tictactoe_be
        image: iarghadip/tictactoe-be:latest
        build:
            context: .
            args:
                - SERVER_KEY=${SERVER_KEY}
        depends_on:
            - cockroachdb
        entrypoint:
            - "/bin/sh"
            - "-ecx"
            - >
                /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
                exec /nakama/nakama --config /nakama/data/local.yml
        ports:
            - "7349:7349"
            - "7350:7350"
            - "7351:7351"

volumes:
    data: