name: tictactoe

database:
    address:
        - root@localhost:26257/nakama?sslmode=disable

runtime:
    js_entrypoint: "src/main.js"

console:
    port: 7351

socket:
    port: 7350
    server_key: "NULL"

api:
    port: 7349